# vim: ft=ansible
---
########################
# Deploy Jenkins Master
########################
- hosts: jenkins_master
  become: true
  tags:
    - jenkins_master

  vars_files:
    - "{{ inventory_dir }}/{{ vars_files_relative }}/vars/main.yml"
    - ~/.ansible/vars/toad_vars.yml

  roles:
    - { role: 'franklinkim.sudo' }
    - { role: 'geerlingguy.repo-epel' }
    - { role: 'geerlingguy.nginx' }
    - { role: 'leifmadsen.jenkins' }

  vars:
    sudo_defaults:
      - defaults: '!requiretty'

  pre_tasks:
    - name: Add jenkins service unit to systemd in case of docker.
      template:
        src: jenkins_systemd.j2
        dest: /etc/systemd/system/jenkins.service
        owner: root
        group: root
        mode: "0655"
      when: deploy_type is defined and deploy_type == 'docker'

  tasks:
    - name: Set facts for later use
      set_fact:
        jenkins_jar_location: "{{ jenkins_jar_location }}"
        jenkins_hostname: "{{ jenkins_hostname }}"
        jenkins_http_port: "{{ jenkins_http_port }}"
        jenkins_url_prefix: "{{ jenkins_url_prefix }}"
        jenkins_admin_username: "{{ jenkins_admin_username }}"
        jenkins_admin_password: "{{ jenkins_admin_password }}"

# In case of docker, jenkins is managed under systemd unit (see above)
    - name: jenkins init script is removed in case of docker
      file:
        path: /etc/init.d/jenkins
        state: absent
      when: deploy_type is defined and deploy_type == 'docker'

    - name: Install python-pip
      yum:
        name: python-pip
        state: present

  post_tasks:
    # Operating system configuration and setup
    - name: Add jenkins user to wheel group
      user:
        name: jenkins
        home: /var/lib/jenkins
        groups: wheel
        append: yes
        shell: /bin/bash

    - name: Update ownership and perms for shadow
      file:
        group: wheel
        mode: "0040"
        path: /etc/shadow

    - name: Create admin user in system
      user:
        name: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password |password_hash('sha512')}}"
        shell: /bin/bash

    - name: Ensure libsemanage-python is installed
      yum:
        name: libsemanage-python
        state: present

    - name: Validate SELinux is enabled
      selinux:
        policy: targeted
        state: permissive
      when: ansible_connection != 'docker'

    - name: SELinux -- Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      when: ansible_connection != 'docker'

    # Copy in configuration for Nginx web proxy fronting Jenkins web UI
    - name: Copy Jenkins Nginx Configuration
      template:
        src: jenkins_master-vhost.conf.j2
        dest: /etc/nginx/conf.d/jenkins_master.conf
        owner: root
        group: root
        mode: "0644"
      notify: restart nginx

    - name: Automate jenkins configuration
      template:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: "{{item.owner}}"
        group: "{{item.group}}"
        mode: "{{item.mode}}"
      notify: restart jenkins
      with_items:
        - src: jenkins_config/config.xml.j2
          dest: /var/lib/jenkins/config.xml
          owner: jenkins
          group: jenkins
          mode: "0644"
        - src: jenkins_config/credentials.xml.j2
          dest: /var/lib/jenkins/credentials.xml
          owner: jenkins
          group: jenkins
          mode: "0644"
        - src: jenkins_config/be.certipost.hudson.plugin.SCPRepositoryPublisher.xml.j2
          dest: /var/lib/jenkins/be.certipost.hudson.plugin.SCPRepositoryPublisher.xml
          owner: jenkins
          group: jenkins
          mode: "0644"

    # Create directory where results from slave workspaces will be copied to.
    - name: Create slave results directory
      file:
        path: "{{ jenkins_master_results_directory }}"
        state: directory
        owner: jenkins
        group: jenkins
        mode: "0755"

#######################
# Deploy Jenkins Slave
#######################
- hosts: jenkins_slave
  tags:
    - jenkins_slave
  become: yes
  roles:
    - { role: 'franklinkim.sudo' }
    - { role: 'geerlingguy.java' }

  vars_files:
    - "{{ inventory_dir  }}/{{ vars_files_relative }}/vars/main.yml"
    - ~/.ansible/vars/toad_vars.yml

  vars:
    sudo_defaults:
      - defaults: '!requiretty'
    sudo_users:
      - name: 'stack'
        nopasswd: yes

  pre_tasks:
    - name: Ensure libselinux-python is installed
      yum:
        name: libselinux-python
        state: present

    - name: Create stack user
      user:
        name: stack
        comment: "Stack Slave User"
        generate_ssh_key: yes

  tasks:
    - name: Validate Git is installed
      yum:
        name: git
        state: present

    - name: Get hostname of slave
      shell: echo $HOSTNAME
      register: jenkins_slave_ssh_hostname
      tags:
        - skip_ansible_lint
        - jenkins_ssh

    - name: Create log directory for images
      file:
          path: /var/log/artib
          state: directory
          owner: stack
          group: stack
          mode: "0755"
      become: true

    - block:
        - name: Unsubscribe previous system
          redhat_subscription:
              state: absent
          ignore_errors: true

        - name: Cleanup previous systems
          command: "subscription-manager remove --all"

        - name: Subscribe for RedHat systems
          redhat_subscription:
              state: present
              username: "{{ rhn_subscription_username }}"
              password: "{{ rhn_subscription_password }}"
              pool: "{{ rhn_subscription_pool_id }}"

        - name: Attach to the desired pool
          command: "subscription-manager attach --pool={{ rhn_subscription_pool_id }}"
          when: rhn_subscription_pool_id is defined

        - name: Unsubscribe to previous repos
          command: "subscription-manager repos --disable=*"
          when: rhn_repos|length > 0

        - name: Subscribe to the list of desired repos
          command: "subscription-manager repos --enable {{ item }}"
          with_items: "{{ rhn_repos }}"
          when: rhn_repos|length > 0
      become: true
      when: ansible_os_family == "RedHat" and rhn_subscription_username is defined and rhn_subscription_password is defined

    - block:
        - name: Install needed packages for reposync
          yum:
              pkg: "{{ item }}"
              state: present
          with_items:
              - createrepo
              - vsftpd
              - yum-utils

        - name: Enable vsftpd service
          service:
              name: vsftpd
              enabled: yes
              state: started

        - name: Check if iptables is running
          command: systemctl is-active iptables
          ignore_errors: yes
          changed_when: false
          register: iptables_service_status

        - name: Open firewall port for input ftp (iptables)
          command: "iptables -A INPUT  -p tcp -m tcp --dport 21 -m conntrack --ctstate ESTABLISHED,NEW -j ACCEPT -m comment --comment 'Allow ftp connections to port 21'"
          when: iptables_service_status.stdout == 'active'

        - name: Open firewall port for output ftp (iptables)
          command: "iptables -A INPUT  -p tcp -m tcp --dport 21 -m conntrack --ctstate ESTABLISHED,NEW -j ACCEPT -m comment --comment 'Allow ftp connections from port 21'"
          when: iptables_service_status.stdout == 'active'

        - name: Open firewall port for ftp (firewall)
          firewalld:
              service: ftp
              permanent: true
              state: enabled
              immediate: true
          when: iptables_service_status.stdout != 'active'

        - name: Check if repo already exists
          stat: path=/tmp/osp_repo
          register: repo_already_exists

        - name: Create temporary directory for mirror
          file:
              path: /tmp/osp_repo
              state: directory
              mode: "0755"
          when: repo_already_exists.stat.exists == False

        - name: Mirror repository locally
          shell: "reposync -l -n -p /tmp/osp_repo/ > /dev/null"
          when: repo_already_exists.stat.exists == False

        - name: Create repositories from local mirror
          shell: "for DIR in `find /tmp/osp_repo  -maxdepth 1 -mindepth 1 -type d`; do createrepo $DIR; done; > /dev/null"
          when: repo_already_exists.stat.exists == False

        - name: Execute repository creation script
          script: "./scripts/create_repo.sh /tmp osp_repo"

      become: true
      when: ansible_os_family == "RedHat" and slave_mirror_sync|bool == true

########################
# Setup SSH connections
########################
- include: jenkins_ssh.yml

###############################
# Add the slaves to the master
###############################
- hosts: jenkins_master
  become: yes
  tags:
    - jenkins_slave

  vars_files:
    - ~/.ansible/vars/toad_vars.yml

  tasks:
    - name: Check if our node already exists
      command: >
        java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
        get-node {{ item }}
        --username {{ jenkins_admin_username }}
        --password {{ jenkins_admin_password }}
      ignore_errors: true
      register: jenkins_cli_get_nodes
      changed_when: false
      when: "'jenkins_slave' in groups"
      with_items:
         - "{{ groups['jenkins_slave'] }}"

    - name: Deploy template for Jenkins slave node
      template:
        src: jenkins_slave.j2
        dest: /tmp/jenkins_slave_{{ item.item }}.tmpl
      when: jenkins_cli_get_nodes is defined and "{{ item.rc }}" != '0'
      with_items:
         - "{{ jenkins_cli_get_nodes.results }}"

    - name: Add Jenkins slave node to the master
      shell: >
        java -jar {{ jenkins_jar_location }} -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix | default('') }}/
        create-node {{ item.item }}
        --username {{ jenkins_admin_username }}
        --password {{ jenkins_admin_password }} < /tmp/jenkins_slave_{{ item.item }}.tmpl
      when: jenkins_cli_get_nodes is defined and "{{ item.rc }}" != '0'
      with_items:
         - "{{ jenkins_cli_get_nodes.results }}"

    - name: Remove template for Jenkins slave node
      file:
        name: /tmp/jenkins_slave_{{ item }}.tmpl
        state: absent
      when: jenkins_cli_get_nodes is defined and "{{ item.rc }}" != '0'
      with_items:
         - "{{ jenkins_cli_get_nodes.results }}"

######################
# Deploy Jenkins jobs
######################
- include: jenkins_jobs.yml
